server:
  servlet:
    contextPath: /api
  port: 8600

spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc.batch_size: 30
        jdbc.time_zone: Europe/Tallinn
  datasource:
    url: jdbc:postgresql://localhost:5422/postgres?currentSchema=public
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

#logging:
#  level:
#    net.ttddyy.dsproxy.listener: DEBUG

